### ISSUE TITLE
When using accelerate launch, `num_machines` is not loaded from `config_file`

### ISSUE THREAD

**Issue by neumyor** [huggingface/accelerate#1217]
### System Info

```Shell
- `Accelerate` version: 0.17.1
- Platform: Linux-5.4.0-48-generic-x86_64-with-glibc2.17
- Python version: 3.8.10
- Numpy version: 1.22.4
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: NO
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 1
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        - dynamo_config: {}
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

To reproduce the bug, 
1. cd `/examples/text_to_image`
2. set up `config.yaml` as 
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
dynamo_config: {}
fsdp_config: {}
gpu_ids: o
machine_rank: 0
main_process_ip: 172.17.0.5
main_process_port: 10000
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 4
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
3. run `accelerate launch --config_file ./config.yaml train_text_to_image.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4"   --dataset_name="lambdalabs/pokemon-blip-captions"   --use_ema   --resolution=512 --center_crop --random_flip   --train_batch_size=1   --gradient_accumulation_steps=4   --gradient_checkpointing   --mixed_precision="fp16"   --max_train_steps=15000   --learning_rate=1e-05   --max_grad_norm=1   --lr_scheduler="constant" --lr_warmup_ss=0`
4. produce error as below
```shell
Traceback (most recent call last):
  File "/root/miniconda3/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 894, in launch_command
    args, defaults, mp_from_config_flag = _validate_launch_command(args)
  File "/root/miniconda3/lib/python3.8/site-packages/accelerate/commands/launch.py", line 806, in _validate_launch_command
    and args.num_machines <= 1
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

### Expected behavior

```Shell
`num_machines` should be `4` as it is set in `config.yaml`
```
