### ISSUE TITLE
How to broadcast the model across all processes while share the same memory-space?

### ISSUE THREAD

**Issue by PeiqinSun** [huggingface/accelerate#1274]
### System Info

```Shell
In torch distributed training, it will 
In pytorch distributed training, loading model from checkpoint will be executed the number of times，resulting in CPU OOM during large model training. Is there any way to load only one copy and then share it among different processes?
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

config yaml
```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
dynamo_config: {}
fsdp_config:
  fsdp_auto_wrap_policy: SIZE_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_min_num_params: 100
  fsdp_offload_params: true
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
machine_rank: 0
main_training_function: main
megatron_lm_config: {}
mixed_precision: fp16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

model = LlamaForCausalLM.from_pretrained("decapoda-research/llama-7b-hf")          

### Expected behavior

The program can run in 64GB cpu memory.
