### ISSUE TITLE
When configuring single GPU, errors occurs

### ISSUE THREAD

**Issue by zengbocheng** [huggingface/accelerate#1316]
### System Info

```Shell
accelerate version=0.18.0
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I can't always get more than 1 GPU. So, sometimes I want to run my code in a single GPU and sometimes in multiple GPUs. However, when I set only one GPU at accelerate.yaml, errors occur.

```shell
ValueError: Less than two GPU ids were configured and tried to run on on multiple GPUs. 
Please ensure at least two are specified for `--gpu_ids`, or use `--gpu_ids='all'`.
```
my accelerate.yaml is
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

### Expected behavior

I just want my code to run in single GPU or multiple GPUs without changing anything except the accelerate.yaml, which is reasonable because one can't ensure to get more than 1 GPU anytime. Hopefully this feature will be considered by developers. Before that, I will continue using pytorch DistributedDataParallel, which meets my requirements.

**Comment by zengbocheng** [comment]
I am sorry. Accelerate can meet my requirements. I just need to change my accelerate.yaml as
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**Comment by zengbocheng** [comment]
I am sorry. Accelerate can meet my requirements. I just need to change my accelerate.yaml as
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
