### ISSUE TITLE
OOM Error on fine-tuning gpt-j-6b

### ISSUE THREAD

**Issue by hsuyab** [huggingface/accelerate#1377]
I am trying to fine-tune `gpt-j-6b` on `wikitext` data using the `run_clm.py` provieded here https://github.com/huggingface/transformers/tree/main/examples/pytorch/language-modeling
I am trying to launch the code as 
```python
accelerate launch run_clm.py \
    --model_name_or_path EleutherAI/gpt-j-6b \
    --dataset_name wikitext \
    --dataset_config_name wikitext-2-raw-v1 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --output_dir /tmp/test-clm
```
I have am trying to use `fsdp` to run this on Nvidia-A100 GPUs each with 40gb memory. I tried running on 2 and 4 GPUs still it is giving Out Of Memory error. I tried by minimising the train_batch_size and eval_batch_size to 1. Not sure if I can run it using accelerate library or not. I thought 40GB x4 A100 GPUs should be okay.

**Comment by sgugger** [comment]
Could you provide us with the result of `accelerate env` as requested in the issue template? Also cc @pacman100

**Comment by pacman100** [comment]
Hello @hsuyab, could you please provide the accelerate config that you are using?

**Comment by pacman100** [comment]
Also, with `accelerate launch` you must use `run_clm_no_trainer.py` and not `run_clm.py`. `run_clm.py` uses Trainer's integration of FSDP with related args mentioned here: https://huggingface.co/docs/transformers/main_classes/trainer#pytorch-fully-sharded-data-parallel

**Comment by hsuyab** [comment]
This is the accelerate config I am using
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: NO_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 0
num_processes: 2
rdzv_backend: static
same_network: true 
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
