### ISSUE TITLE
Can't specify a gpu to run

### ISSUE THREAD

**Issue by 631068264** [huggingface/accelerate#1474]
### System Info

```Shell
Copy-and-paste the text below in your GitHub issue

- `Accelerate` version: 0.19.0
- Platform: Linux-4.15.0-210-generic-x86_64-with-glibc2.17
- Python version: 3.8.16
- Numpy version: 1.24.3
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- System RAM: 251.90 GB
- GPU type: NVIDIA A100 80GB PCIe
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Use  this https://github.com/OpenLMLab/MOSS/blob/main/finetune_moss.py to finetune
I add code on the top
```
"""Code for moss-sft"""

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
```
just like this https://github.com/OpenLMLab/MOSS/issues/312   get error， I don't know why it use GPU:0

sft.yaml
```yaml
command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: fp16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false

```

shell

```sh
num_machines=1
num_processes=$((num_machines * 1))
machine_rank=0
#CUDA_VISIABLE_DEVICES=1
accelerate launch \
	--config_file ./configs/sft.yaml \
	--num_processes $num_processes \
	--num_machines $num_machines \
	--machine_rank $machine_rank \
	--deepspeed_multinode_launcher standard finetune_moss.py \
	--model_name_or_path /data/home/yaokj5/dl/apps/moss_new/model/moss-moon-003-sft \
	--data_dir ./data \
	--output_dir ./ckpts/moss-moon-003-sft \
	--log_dir ./train_logs/moss-moon-003-sft \
	--n_epochs 2 \
	--train_bsz_per_gpu 4 \
	--eval_bsz_per_gpu 4 \
	--learning_rate 0.000015 \
	--eval_step 200 \
	--save_step 2000 
	

```

then  use gpu_ids   get error  ` error: unrecognized arguments: --gpu_ids=1`

```
num_machines=1
num_processes=$((num_machines * 1))
machine_rank=0
#CUDA_VISIABLE_DEVICES=1
accelerate launch \
	--config_file ./configs/sft.yaml \
	--num_processes $num_processes \
	--num_machines $num_machines \
	--machine_rank $machine_rank \
	--deepspeed_multinode_launcher standard finetune_moss.py \
	--model_name_or_path /data/home/yaokj5/dl/apps/moss_new/model/moss-moon-003-sft \
	--data_dir ./data \
	--output_dir ./ckpts/moss-moon-003-sft \
	--log_dir ./train_logs/moss-moon-003-sft \
	--n_epochs 2 \
	--train_bsz_per_gpu 4 \
	--eval_bsz_per_gpu 4 \
	--learning_rate 0.000015 \
	--eval_step 200 \
	--save_step 2000 \
	--gpu_ids='1'
```

### Expected behavior

I want to just use GPU:1 to train
