### ISSUE TITLE
Setting up _other_megatron_args in Accelerate config file has no effect

### ISSUE THREAD

**Issue by leocnj** [huggingface/accelerate#1791]
Inspired by this [tutorial of setting up additional Megatron-LM args](https://huggingface.co/docs/accelerate/usage_guides/megatron_lm#support-for-rope-and-alibi-positional-embeddings-and-multiquery-attention), I created the following Accelerate config yaml file.

However, when running the `example/by_feature/megatron_lm_gpt_pretraining.py`, both `attention_head_type` and `position_embedding_type` are NOT changed according to the config file.

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MEGATRON_LM
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
megatron_lm_config:
  megatron_lm_gradient_clipping: 1.0
  megatron_lm_pp_degree: 1
  megatron_lm_recompute_activations: true
  megatron_lm_tp_degree: 1
  megatron_lm_sequence_parallelism: true
  megatron_lm_use_distributed_optimizer: true
  megatron_lm_other_megatron_args:
    attention_head_type: 'multiquery'
    position_embedding_type: 'rotary'
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false
```
Does any one know how to properly use `_other_megatron_args`?
