### ISSUE TITLE
`zero3_init_flag:true` does not activate `zero.init()` for `transformers` models

### ISSUE THREAD

**Issue by lewtun** [huggingface/accelerate#1801]
### System Info

```Shell
- `Accelerate` version: 0.21.0.dev0
- Platform: Linux-5.15.0-1023-aws-x86_64-with-glibc2.31
- Python version: 3.10.11
- Numpy version: 1.24.3
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- PyTorch XPU available: False
- System RAM: 1121.82 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: bf16
        - use_cpu: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I'm trying to activate DeepSpeed's Zero-3 `zero.init()` for `transformers` models with the `accelerate` launcher. Ordinarily, I would expect to see the following message in the [logs](https://github.com/huggingface/transformers/blob/0fd8d2aa2cc9e172a8af9af8508b2530f55ca14c/src/transformers/modeling_utils.py#L1140) when `zero3_init_flag: true` is set in the `accelerate` config (full config below):

```
Detected DeepSpeed ZeRO-3: activating zero.init() for this model
```

However, I'm finding this is not the case _unless_ I use the default `accelerate` config _and_ provide a path to a separate DeepSpeed config JSON using the `transformers.TrainingArguments.deepspeed` argument. Is some additional step required to activate `zero.init()` for `transformers` models with `accelerate`?

Steps to reproduce are provided below.

1. Create `main.py` with the following contents:

```py
# main.py
from transformers import AutoModelForCausalLM, HfArgumentParser, TrainingArguments
from dataclasses import dataclass

@dataclass
class ModelArguments:
    model_name_or_path: str

def main():
    parser = HfArgumentParser((ModelArguments, TrainingArguments))
    model_args, training_args = parser.parse_args_into_dataclasses()
    model = AutoModelForCausalLM.from_pretrained(
            model_args.model_name_or_path,
        )

if __name__ == "__main__":
    main()
```

2. Create `accelerate_ds3.yaml` with DeepSpeed ZeRO-3 attributes:

```yaml
# accelerate_ds.yaml
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  gradient_clipping: 1.0
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

3. Run the following command with a small model (note, no `Detected DeepSpeed ZeRO-3: activating zero.init() for this model
` message will appear in the logs):

```shell
ACCELERATE_LOG_LEVEL=info TRANSFORMERS_VERBOSITY=info accelerate launch --config_file=accelerate_ds3.yaml main.py --output_dir=scratch --model_name_or_path=EleutherAI/pythia-70m
```

4. As a point of comparison, now use the default `accelerate` config:

```yaml
accelerate_default.yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: 0,1
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

and now run with the `--deepspeed` argument from `transformers.TrainingArguments` (now the `Detected DeepSpeed ZeRO-3: activating zero.init() for this model` message will appear in the logs):

```shell
ACCELERATE_LOG_LEVEL=info TRANSFORMERS_VERBOSITY=info accelerate launch --config_file=accelerate_default.yaml main.py --output_dir=scratch --model_name_or_path=EleutherAI/pythia-70m --deepspeed=deepspeed_z3_config.json
```

where `deepspeed_z3_config.json` is the following config:

```json
{
  "bf16": {
    "enabled": "auto"
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },
  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": "auto",
      "warmup_max_lr": "auto",
      "warmup_num_steps": "auto"
    }
  },
  "zero_optimization": {
    "stage": 3,
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": 1e9,
    "reduce_bucket_size": "auto",
    "stage3_prefetch_bucket_size": "auto",
    "stage3_param_persistence_threshold": "auto",
    "stage3_max_live_parameters": 1e9,
    "stage3_max_reuse_distance": 1e9,
    "stage3_gather_16bit_weights_on_model_save": true
  },
  "gradient_accumulation_steps": "auto",
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

As far as I can tell, `_hf_deepspeed_config_weak_ref` isn't being set when `zero3_init_flag: true`, but apologies if this is simply user error. I also wasn't sure whether to open this issue in `accelerate` or `transformers`, so please let me know if you'd like it moved.

### Expected behavior

Seeing evidence in the logging that `zero.init()` is being activated for a model when `zero3_init_flag: true`. As far as I can tell, this isn't being activated since loading large models like Falcon 40B is making the CPU go OOM (which shouldn't happen with `zero.init()`)
