### ISSUE TITLE
Data sharding accross the nodes is not happening with Deepspeed

### ISSUE THREAD

**Issue by dineshkh** [huggingface/accelerate#1867]
I am running a training on `2 Nodes` with `8 GPUs` each. I have noticed that sharding of dataloader is not happening when I am using Deepspeed whereas it is happening when I using FSDP. 

Details of my environment: 

`accelerate                0.20.3                   pypi_0    pypi` 
`deepspeed                 0.10.1                   pypi_0    pypi`
`pytorch                   2.0.1           py3.11_cuda11.7_cudnn8.5.0_0    pytorch`

My accelerate config for deepspeed:

```
compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: false
  zero_stage: 3
machine_rank: 0
main_process_ip: 178.192.12.13
main_process_port: 57709
main_training_function: main
mixed_precision: 'bf16'
num_machines: 2
num_processes: 16
use_cpu: false
```

In log Deepspeed is printing the `world_size` as `8` which should be `16`:
```
[2023-08-20 07:58:12,783] [INFO] [launch.py:163:main] dist_world_size=8
[2023-08-20 07:58:18,992] [INFO] [launch.py:163:main] dist_world_size=8
[2023-08-20 07:59:02,449] [INFO] [config.py:964:print]   world_size ................... 8
[2023-08-20 07:59:05,617] [INFO] [config.py:964:print]   world_size ................... 8
```

Size of Train loader `3382` in case of Deepspeed.
Size of Train loader `1691` in case of FSDP.

I think Deepspeed is not getting correct `world_size` though `num_processes: 16` is in the config file.
