### ISSUE TITLE
Accelerator#_prepare_fsdp turns AdamW 8-bit optimizer into AdamW 32-bit

### ISSUE THREAD

**Issue by scottlogic-alex** [huggingface/accelerate#1902]
### System Info

```Shell
- `Accelerate` version: 0.21.0
- Platform: Linux-5.19.0-45-generic-x86_64-with-glibc2.35
- Python version: 3.11.2
- Numpy version: 1.25.2
- PyTorch version (GPU?): 2.1.0.dev20230802+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 62.79 GB
- GPU type: NVIDIA A40
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: FSDP
        - mixed_precision: bf16
        - use_cpu: False
        - num_processes: 2
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - fsdp_config: {'fsdp_auto_wrap_policy': 'TRANSFORMER_BASED_WRAP', 'fsdp_backward_prefetch_policy': 'NO_PREFETCH', 'fsdp_forward_prefetch': False, 'fsdp_offload_params': False, 'fsdp_sharding_strategy': 1, 'fsdp_state_dict_type': 'SHARDED_STATE_DICT', 'fsdp_sync_module_states': True, 'fsdp_transformer_layer_cls_to_wrap': 'LlamaDecoderLayer', 'fsdp_use_orig_params': True}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Training script is a [fork of `qlora.py`](https://github.com/scottlogic-alex/qlora/blob/d5e564ad3affcaf62c22912ba36cab2d77c2d585/qlora.py).

But if you have a preferred script, go ahead and use that; the triggers are:

- FSDP enabled
- AdamW 8-bit optimizer selected

### Configure accelerate

Set up your accelerate config (`~/.cache/huggingface/accelerate/default_config.yaml`) like so:

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: NO_PREFETCH
  fsdp_forward_prefetch: false
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_sync_module_states: true
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
  fsdp_use_orig_params: true
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

### Set up repository

```bash
git clone https://github.com/scottlogic-alex/qlora.git
cd qlora
git checkout d5e564ad3affcaf62c22912ba36cab2d77c2d585
pip install -U -r requirements.txt
```

### Run trainer

We will run `qlora.py` on 2xA40, non-distributed (it's one coreweave computer with 2 GPUs).  
This config will atempt to run a full finetune of Llama 2 7b.

```bash
python -m accelerate.commands.launch qlora.py --use_auth_token True --model_name_or_path meta-llama/Llama-2-7b-chat-hf --trust_remote_code --dataset prm800k-solutions --dataset_format prm800k-solutions --max_memory_MB 48000 --simulate_worst_case_seq_len --truncate_toward_center --source_max_len 2048 --target_max_len 2048 --gradient_accumulation_steps 2 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --optim adamw_8bit --learning_rate 0.0002 --save_steps 196 --save_total_limit 1 --max_steps 256 --evaluation_strategy steps --eval_steps 196 --measure_memory --terminate_after_step 16 --bits 32 --full_finetune 
```

### Verify that optimizer begins as 8-bit

I placed a breakpoint at the end of `transformers.trainer::Trainer#create_optimizer`:  
https://github.com/huggingface/transformers/blob/4c21da5e347bfc53ee4ec5b71a23721fefe6822c/src/transformers/trainer.py#L1001

`self.optimizer.args.optim_bits == 8`, as expected of AdamW 8-bit:

<img width="962" alt="image" src="https://github.com/huggingface/accelerate/assets/40387940/58ba0c81-ce36-4c07-9a24-a6ffb9bf3beb">

### Verify that `accelerate` recreates our optimizer as AdamW 32-bit

I placed a breakpoint in `accelerate.accelerator::Accelerator#_prepare_fsdp`:  
https://github.com/huggingface/accelerate/blob/bc86a9379f555f67504b9877171c66e4c588bd14/src/accelerate/accelerator.py#L1114

Observe how the optimizer that's submitted to `_prepare_fsdp` is the same 8-bit AdamW that we saw earlier:  
<img width="871" alt="image" src="https://github.com/huggingface/accelerate/assets/40387940/1a1d36d7-5f40-47e6-9954-74ed3717c025">

_Side-note: construction fails, due to `differentiable` arg present in `obj.optimizer.defaults` (https://github.com/huggingface/accelerate/issues/801), so it falls-back to removing the `differentiable` arg and trying again:_
<img width="870" alt="image" src="https://github.com/huggingface/accelerate/assets/40387940/9ad1db47-7231-4029-bfab-b69cab61a333">

After `accelerate` creates our new optimizer, observe how it's **not the same as before**; `obj.optimizer.args.optim_bits != optimizer.args.optim_bits`:  
<img width="866" alt="image" src="https://github.com/huggingface/accelerate/assets/40387940/395398df-3786-4abe-88cc-ce01fd8e7a39">

### Run out of memory

Since our 8-bit optimizer got turned into a 32-bit optimizer: we don't have enough memory to full-finetune Llama 7b in mixed-precision on 2xA40. 😢 

<img width="1477" alt="image" src="https://github.com/huggingface/accelerate/assets/40387940/736a8b00-699e-4436-bae8-5138ff28ad35">

### Expected behavior

When accelerate prepares our optimizer for FSDP: 8-bit optimizers should **remain** 8-bit after preparation. 🙃
