### ISSUE TITLE
fsdp example has an error

### ISSUE THREAD

**Issue by hamelsmu** [huggingface/accelerate#1943]
### System Info

When running [this example](https://huggingface.co/docs/accelerate/usage_guides/fsdp) got  Exception("Could not find the transformer layer class to wrap in the model.")

Running 
```
accelerate launch examples/nlp_example.py
```

With this config

```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: GPT2Block
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 2
use_cpu: false
```

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

Run the code in the docs as-is

### Expected behavior

Shouldn't get an error when running code in the docs as-is
