### ISSUE TITLE
Size of the saved model checkpoint after extending pretraining using FSDP is larger than that of the base model.

### ISSUE THREAD

**Issue by dineshkh** [huggingface/accelerate#1958]
I am do extended pretraining of a 20B model using FSDP. I observe that the size of model saved after extended pretraining is larger than the base model. This is how I am saving the model. 

```
       unwrapped_model = accelerator.unwrap_model(model)   
        state_dict = None
        if os.environ.get("ACCELERATE_USE_FSDP") == "true":
            logger.info(f'using ACCELERATE plugin')
            full_state_dict_config = FullStateDictConfig(offload_to_cpu=True, rank0_only=True)
            with FSDP.state_dict_type(unwrapped_model,
                                      StateDictType.FULL_STATE_DICT, full_state_dict_config):
                state_dict = accelerator.get_state_dict(unwrapped_model)
        if accelerator.is_main_process:
            unwrapped_model.save_pretrained(
                output_dir,
                is_main_process=accelerator.is_main_process,
                save_function=accelerator.save,
                state_dict=state_dict,
                safe_serialization=FLAGS.safe_serialization
            )
```
I am using `safetensors` for saving the model. 

Size of base model on disk:

<img width="662" alt="image" src="https://github.com/huggingface/accelerate/assets/14121108/9e1840ad-624c-4d25-a7e3-42195271919e">

Size of extended pretrained model on disk:

<img width="803" alt="image" src="https://github.com/huggingface/accelerate/assets/14121108/125584c2-198b-4cbc-8737-885d2f8abb10">

If you see size of last shard has increased from `1359201312` to `2567185552`
Any reason of this behavior ?

Following is my FSDP configuration:
```
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: NO_PREFETCH
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: GPTBigCodeBlock
machine_rank: 0
main_process_ip: 172.168.12.19
main_process_port: 55930
main_training_function: main
mixed_precision: 'bf16'
num_machines: 10
num_processes: 80
use_cpu: false
```

I am using `accelerate==0.20.3`. My transformers and torch version are following:

`transformers              4.29.0                   pypi_0    pypi`
`torch                     2.0.1                    pypi_0    pypi`
