### ISSUE TITLE
model.save_pretrained after FSDP malfunctioning

### ISSUE THREAD

**Issue by nebrelbug** [huggingface/accelerate#2025]
### System Info

```Shell
- `Accelerate` version: 0.23.0
- Platform: Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.35
- Python version: 3.10.12
- Numpy version: 1.26.0
- PyTorch version (GPU?): 2.1.0a0+32f93b1 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 2003.87 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

`main.py`
```python
from transformers import LlamaForCausalLM, LlamaTokenizer
from accelerate import Accelerator

accelerator = Accelerator()

SIZE = "7b"
MODEL_PATH = f"/mnt/models/llama2/hf/Llama-2-{SIZE}-hf"
NAME = f"test-model-{SIZE}"

tokenizer = LlamaTokenizer.from_pretrained(MODEL_PATH, legacy=False)
tokenizer.pad_token = tokenizer.eos_token

model = LlamaForCausalLM.from_pretrained(MODEL_PATH)
model.generation_config.do_sample = True
model = accelerator.prepare(model)

unwrapped_model = accelerator.unwrap_model(model)

# see https://huggingface.co/docs/accelerate/v0.23.0/en/usage_guides/fsdp#saving-and-loading
unwrapped_model.save_pretrained(
    f"/mnt/finetunes/{NAME}",
    is_main_process=accelerator.is_main_process,
    save_function=accelerator.save,
    state_dict=accelerator.get_state_dict(model)
)

if accelerator.is_main_process:
    tokenizer.save_pretrained(f"/mnt/finetunes/{NAME}")
```

`accelerate_config.yaml`
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: 1
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: LlamaDecoderLayer
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 8
use_cpu: false
```

`launch.sh`
```
accelerate launch --config_file ./accelerate_config.yaml loop.py
```

### Expected behavior

I'm having issues using `save_from_pretrained`.

If I load and prepare a Llama model using Accelerate with FSDP, then try to save it, it no longer outputs reasonable completions -- instead, it outputs gobbledy-gook like "когокогокогокогокогокогокогокогокогокогокогокого..." or "Zwemission banksmission banksmission banksmission banksmission banksmission..."

Here's the code I use to test the generated model:

```py
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

template = """### Instruction:
{instruction}

### Response:
"""

model_path = f"/mnt/finetunes/zz-7b-7"

tokenizer = AutoTokenizer.from_pretrained(model_path, legacy=False)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    model_path, device_map="auto", local_files_only=True
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    return_full_text=False,
    do_sample=True,
    temperature=0.9,
    max_new_tokens=200,
)

def prompt_model():
    prompt = input("Enter your question: ")
    prompt = template.format(instruction=prompt)
    answer = pipe(prompt)
    print(answer[0]["generated_text"])


def main():
    print(f"Welcome to {model}!")

    while True:
        prompt_model()

if __name__ == "__main__":
    main()
```
