### ISSUE TITLE
Multi-GPU performance worse than single GPU

### ISSUE THREAD

**Issue by GabPrato** [huggingface/accelerate#2027]
### System Info

```Shell
accelerate 0.22.0
cuda-runtime 11.8.0 0 nvidia
cuda-version 11.8 h70ddcb2_2 conda-forge
cudatoolkit 11.8.0 h4ba93d1_12 conda-forge
cudnn 8.8.0.121 h838ba91_3 conda-forge
python 3.10.12 hd12c33a_0_cpython conda-forge
pytorch 2.0.1 py3.10_cuda11.8_cudnn8.7.0_0 pytorch
pytorch-cuda 11.8 h7e8668a_5 pytorch
transformers 4.33.1 pypi_0 pypi
deepspeed==0.10.3
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [ ] My own task or dataset (give details below)

### Reproduction

I noticed that performance with my own scripts was worse with multi-gpu than with single gpu. I tried the `nlp_examply.py` in the examples of the official repo and notice the performance is slightly worse. I only averaged over 3 seeds for nlp_examply, so maybe it's just because of variance, but in my own scripts, the gap is very noticeable.

What I did with `nlp_example.py`:
1. Single GPU accelerate config:
```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: 'NO'
downcast_bf16: 'no'
gpu_ids: '0'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
2. Set the number of epochs to 50 in `nlp_example.py`
3. Ran `accelerate launch --config_file=accelerate_config.yaml nlp_example.py --mixed_precision=bf16`
4. Set the two gpu accelerate config:
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 1
  zero3_init_flag: false
  zero_stage: 0
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
5. Reduced the batch size in `nlp_example.py` to 8 such that the total batch size is 16.
6. Ran `accelerate launch --config_file=accelerate_config_2gpus.yaml nlp_example.py --mixed_precision=bf16`

Repeated this for 3 different seeds. I get the following results:
![temp_accuracy](https://github.com/huggingface/accelerate/assets/25964820/9fe39516-845b-424b-bd5d-594a03f16b99)
![temp_f1](https://github.com/huggingface/accelerate/assets/25964820/66978322-30e3-40ee-8a4f-0596a67be8ff)

Not sure if this is a DeepSpeed, accelerate or torch issue.

### Expected behavior

Performance shouldn't be worse.
