### ISSUE TITLE
AttributeError: 'FP16_DeepSpeedZeroOptimizer' object has no attribute 'defaults' with DeepSpeed

### ISSUE THREAD

**Issue by Chris-hughes10** [huggingface/accelerate#208]
Hi, 

I'm trying to run the `cv_example.py` script using Deepspeed, but I keep running into the following error. I am using deepspeed==0.5.8 and the `torch.optim.Adam` optimizer:

```
  File "/anaconda/envs/py37_pytorch/lib/python3.7/site-packages/accelerate/optimizer.py", line 77, in defaults
    return self.optimizer.defaults
AttributeError: 'FP16_DeepSpeedZeroOptimizer' object has no attribute 'defaults'
```

The only modification that I have made to the script is to add the line:
```
parser.add_argument("--local_rank", required=False, type=int)
```
which DeepSpeed requires.

My accelerate config is:
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  zero_stage: 2
distributed_type: DEEPSPEED
fp16: false
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
```

Is this something that you have seen before?

Thanks,
Chris
