### ISSUE TITLE
how to turn off fp16 auto_cast?

### ISSUE THREAD

**Issue by haorannlp** [huggingface/accelerate#2474]
i notice that the deepspeed config always set my `auto_cast=True` and this is my data
``` 
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_multinode_launcher: standard
  gradient_clipping: 1.0
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero3_offload_param_pin_memory: true
  zero3_offload_optimizer_pin_memory: true
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
  max_live_parameters: 1e9
  max_reuse_distance: 1e9
  round_robin_gradients: true
  deepspeed_hostfile: /opt/tiger/hostfile
distributed_type: DEEPSPEED
fsdp_config: {}
main_training_function: main
mixed_precision: fp16
use_cpu: false

```

this is my deepspeed log:
``` 
[2024-02-21 19:35:40,143] [INFO] [config.py:958:print_user_config]   json = {
    "train_batch_size": 512, 
    "train_micro_batch_size_per_gpu": 64, 
    "gradient_accumulation_steps": 1, 
    "zero_optimization": {
        "stage": 3, 
        "offload_optimizer": {
            "device": "cpu", 
            "nvme_path": null
        }, 
        "offload_param": {
            "device": "cpu", 
            "nvme_path": null
        }, 
        "stage3_gather_16bit_weights_on_model_save": true
    }, 
    "gradient_clipping": 1.0, 
    "steps_per_print": inf, 
    "fp16": {
        "enabled": true, 
        "auto_cast": true
    }, 
    "bf16": {
        "enabled": false
    }, 
    "zero_allow_untested_optimizer": true
}
```
