### ISSUE TITLE
Error with Deepspeed and dataloader_drop_last=True when batch size doesn't divide evenly

### ISSUE THREAD

**Issue by mrbesher** [huggingface/accelerate#2801]
### System Info

```Shell
- `Accelerate` version: 0.30.1
- Platform: Linux-5.15.133+-x86_64-with-glibc2.31
- `accelerate` bash location: /opt/conda/bin/accelerate
- Python version: 3.10.13
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.1.2 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 31.36 GB
- GPU type: Tesla T4
- `Accelerate` default config:
	Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

When I drop the last batch in the dataloader when training with Deepspeed, I get an error if the evaluation dataset's size is not a multiple of the number of the total batch size (`num_gpus * per_device_eval_batch_size`).

> I cannot set `dataloader_drop_last` to `False` as it causes another issue where the loss becomes `None` (unable to reproduce on the current device).

Simple code to reproduce the issue:

```python
from datasets import Dataset
from transformers import TrainingArguments
from trl import SFTTrainer

model_id = "openai-community/gpt2"

dataset = Dataset.from_list([{
    "text": "The Middle English word bugge is the basis for the terms bugbear and bugaboo as terms used for a monster."
}] * 14)

training_args = TrainingArguments(
        "output",
        report_to="none",
        dataloader_drop_last=True,
        per_device_eval_batch_size=8)

trainer = SFTTrainer(
        model_id,
        args=training_args,
        eval_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=16
    )

trainer.evaluate()
```

Accelerate config:

```yaml
compute_environment: LOCAL_MACHINE
debug: true
deepspeed_config:
  gradient_accumulation_steps: 1
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

Error message:

```
Traceback (most recent call last):
  File "/kaggle/working/./mycode.py", line 21, in <module>
    trainer.evaluate()
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3572, in evaluate
    output = eval_loop(
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3757, in evaluation_loop
    loss, logits, labels = self.prediction_step(model, inputs, prediction_loss_only, ignore_keys=ignore_keys)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3924, in prediction_step
    has_labels = False if len(self.label_names) == 0 else all(inputs.get(k) is not None for k in self.label_names)
  File "/opt/conda/lib/python3.10/site-packages/transformers/trainer.py", line 3924, in <genexpr>
    has_labels = False if len(self.label_names) == 0 else all(inputs.get(k) is not None for k in self.label_names)
AttributeError: 'NoneType' object has no attribute 'get'
```

Some libraries' versions:
```
trl==0.8.6
transformers==4.41.1
accelerate==0.30.1
deepspeed==0.14.2
```

Please let me know if you need any further information.

### Expected behavior

I expect the evaluate method to complete successfully without throwing an AttributeError when the evaluation dataset's size is not a multiple of the total batch size. The trainer should be able to handle the uneven batch size by dropping the last batch and proceeding with the evaluation.
