### ISSUE TITLE
accelerate Inappropriate convert all inputs to specific dtype

### ISSUE THREAD

**Issue by rangehow** [huggingface/accelerate#2811]
As title said, I made a minium snippet like this:
```python

from transformers import ,Trainer



class MyTrainer(Trainer):
  def compute_loss(inputs):
        input_ids = inputs.pop("input_ids")
        attention_mask = inputs.pop("attention_mask")
  
        valid_label_index_list = inputs.pop(
            "valid_label_index_list"
        ) 
        all_prob_supervised = inputs.pop("all_prob_supervised")
        all_prob_clm = inputs.pop("all_prob_clm")
        supervised_cnt = inputs.pop("supervised_cnt")
        clm_cnt = inputs.pop("clm_cnt")
  
        result = model(
              input_ids=input_ids,
              attention_mask=attention_mask,
          )
```
If we set amp to 'bfloat16', all element in `inputs` will be convert from float32 to bfloat16.
While amp supported by huggingface trainer argument will not do this. So I am not sure if this is a feature of accelerate or just a bug?
If this  is a feature, how can we avoid this? (Since other input like `clm_cnt` in the case won't go into model, so there is no need to convert them to bf16)

```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 8
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: false
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

```

**System info (please complete the following information):**
 - GPU count and types 2xA100
 - Python version 3.11
 - deepspeed 0.14.2
 - accelerate 0.30.0
 - transformers 4.40.2
 - cuda 12.2
