### ISSUE TITLE
Question about `float16` when load the model

### ISSUE THREAD

**Issue by AIR-hl** [huggingface/accelerate#2918]
### System Info

```Shell
- `Accelerate` version: 0.30.1
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.35
- `accelerate` bash location: /root/miniconda3/bin/accelerate
- Python version: 3.10.8
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 944.84 GB
- GPU type: NVIDIA L20
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

When I only use `tranformers` without `accelerate`, I can't load the model in `flaot16` through `from_pretrained` and set `fp16=True` in `TrainingArguments` at the same time for pure fp16 training. if I want to use fp16, I must load the model in `float32`, as this [reply](https://github.com/huggingface/transformers/issues/30100#issuecomment-2042857181) from `transformers`

But I found that I can load the model in `float16` and set `fp16=True` when launching the script by using `deepspeed` through `accelerate`. Therefore, I would like to know what causes this difference, is it pure fp16 training if I load the model in `float16` and set `fp16=True` and set `mixed_precision: no` 

```python
from transformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrain(model_path, 
                                           device_map='auto',
                                           torch_dtype=torch.float16)

```

btw, I found the `mixed_precision`  seems to have no effect. I set it `bf16` and set `fp16` in `transformers` TrainingArguments and load model in `float32`，it wont appear any error, why this happened?

```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

### Expected behavior

no
