### ISSUE TITLE
get_state_dict() Does Not Unwrap FSDP Models

### ISSUE THREAD

**Issue by alex-jw-brooks** [huggingface/accelerate#2958]
### System Info

```Shell
- `Accelerate` version: 0.32.1
- Platform: Linux-4.18.0-372.71.1.el8_6.x86_64-x86_64-with-glibc2.34
- `accelerate` bash location: /home/tuning/.local/bin/accelerate
- Python version: 3.11.7
- Numpy version: 1.26.4
- PyTorch version (GPU?): 2.3.1+cu121 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- PyTorch MLU available: False
- System RAM: 2003.72 GB
- GPU type: NVIDIA A100-SXM4-80GB
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [x] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

There appears to be an issue with saving models when FSDP is enabled through the HuggingFace Trainer. Internally, the trainer calls `get_state_dict()` ([here](https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py#L3434)) on its internally held accelerate object with the default `unwrap=True` value, but this value does not appear to be used in the case of FSDP models ([here](https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L3288)).

This appears to cause potential inconsistencies in the way that the model is exported, specifically when it comes to the way that tied weights/shared pointers are resolved. With the current code, the data pointers for the tied weights may be different, which means that the trainer will not resolve and delete the shared pointer, and will instead save them as separate duplicated weights. This can lead to issues in optimized runtimes that are leveraging models that were trained with FSDP through the HF trainer / accelerate, e.g., [vllm](https://github.com/vllm-project/vllm), which for the repro case below, doesn't expect an lm head to be present in the model that has its lm head and embeddings tied.

I've tried to create a minimal repro case for discussion based on how the accelerator that was getting created in my script through the trainer.

Using the following FSDP config:
```yaml
# options that can be used with accelerate config are neatly documented here - 
# https://github.com/huggingface/accelerate/blob/ee163b66fb7848892519e804688cb4ae981aacbe/docs/source/package_reference/cli.md

# type of compute environment, no need to change
compute_environment: LOCAL_MACHINE # AMAZON_SAGEMAKER

# use FSDP distributed compute
distributed_type: FSDP

# FSDP specific configurations
fsdp_config:
  
  # use this for training transformers
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP

  # this controls the FSDP pipelining
  fsdp_backward_prefetch_policy: BACKWARD_PRE # set to BACKWARD_PRE for the most time-efficient pipeline
                                              # but requires the most memory. BACKWARD_POST is the less
                                              # memory intensive option

  # setting this to true will increase forward memory by prefetching the next FSDP all-gather, while performing
  # the current forward pass. 
  fsdp_forward_prefetch: false

  # setting this will offload model and optimizer parameters to the CPU, to save GPU memory at a significant
  # increase of CPU time.
  fsdp_offload_params: false
  
  fsdp_sharding_strategy: 1 # set to FULL_SHARD (1), SHARD_GRAD_OP (2), 
                            # 3 is NO_SHARD, effectively disabling FSDP
                            # 4, 5 are HYBRID_ modes for multi-node training only.

  fsdp_state_dict_type: FULL_STATE_DICT # set to FULL_STATE_DICT (1), SHARDED_STATE_DICT (3)
                                        # 2 is LOCAL_STATE_DICT where parameters are still flattened
                                        # 3 is efficient, but requires know-how to use the shared checkpoint.
 
  fsdp_cpu_ram_efficient_loading: true # for large models set to true, model loaded on single process
  fsdp_sync_module_states: true # for large models set to true, model loaded on single process

  # not needed for HF models that have . _no_split_modules
  # the example below is for GPTBigCode
  # fsdp_transformer_layer_cls_to_wrap: "GPTBigCodeBlock” 

# for "autocast" mixed precision training, where the weights of the model are kept at higher precision, but the 
# learning products (e.g., gradients, model parameters) are kept at a lower precision. Default is 'no'. Other options
# would be fp16, bf16, etc.
mixed_precision: 'no'

machine_rank: 0 # rank of the machine where accelerate is launched
num_machines: 1
num_processes: 1  # default, override with --num_processes

# the rendezvous method to use in distributed training. Other option is c10d
rdzv_backend: static
same_network: true

# below arguments are required when training in multi-node setup
# for multi-gpu single node, the below values default to
# main_process_ip: 127.0.0.1 # override with --main_process_ip
# main_process_port: 29500 # override with --main_process_port
```

Run this script: 
```python
import os
import accelerate
import transformers


if __name__ == "__main__":
    accelerator_args = {
        'deepspeed_plugin': None,
        'gradient_accumulation_plugin': accelerate.utils.GradientAccumulationPlugin(
            num_steps=1,
            adjust_scheduler=True,
            sync_with_dataloader=False,
            sync_each_batch=False
        ), 'dataloader_config': accelerate.utils.DataLoaderConfiguration(
            split_batches=False,
            dispatch_batches=None,
            even_batches=True,
            use_seedable_sampler=True,
            non_blocking=False)
    }
    model = transformers.AutoModelForCausalLM.from_pretrained ("ibm-granite/granite-8b-code-base")
    model_state_dict = model.state_dict()
    # Get the underlying ptr to the tied weights
    lm_head_ptr_no_acc = model_state_dict["lm_head.weight"].untyped_storage().data_ptr()
    emb_ptr_no_acc = model_state_dict["model.embed_tokens.weight"].untyped_storage().data_ptr()

    accelerator = accelerate.Accelerator(**accelerator_args)
    if accelerator.state.is_main_process:
        # These values are always the same
        print(f"Lm head ptr [no accelerate] {lm_head_ptr_no_acc}")
        print(f"Emb ptr [no accelerate] {emb_ptr_no_acc}")

    # Now do the same with our FSDP config
    acc_model = accelerator.prepare(model)
    # These values aren't the same even though get_state_dict should unwrap the model by default
    # acc_model = accelerator.unwrap_model(acc_model)
    accelerate_state_dict = accelerator.get_state_dict(acc_model, unwrap=True)
    if "lm_head.weight" in accelerate_state_dict:
        print(f"Lm head ptr [accelerate]: {accelerate_state_dict['lm_head.weight'].untyped_storage().data_ptr()}")
    if "model.embed_tokens.weight" in accelerate_state_dict:
        print(f"Em ptr [accelerate]: {accelerate_state_dict['model.embed_tokens.weight'].untyped_storage().data_ptr()}")
```

Then run via `accelerate launch` with 2 processes: `accelerate launch --config_file accelerate_fsdp_defaults.yaml --num_processes 2 /app/repro.py`

In the environment I am testing in, the pointers for the embedding / lm head are different only when using FSDP:
```
Lm head ptr [no accelerate] 140098142203968
Emb ptr [no accelerate] 140098142203968

Lm head ptr [accelerate]: 140010312249408
Em ptr [accelerate]: 140042139836480
```

### Expected behavior

Pointers that are the same in the `state_dict` for Pytorch should also be the same when fetching the `state_dict` through Accelerate's `get_state_dict()` so that libraries like `transformers` which have logic for removing shared pointers create consistent models.
