### ISSUE TITLE
DeepSpeed integration doesn't seem to work with generated config

### ISSUE THREAD

**Issue by m3rlin45** [huggingface/accelerate#302]
I have used `accelerate config` to generate config that uses deepspeed

Config:
```
compute_environment: LOCAL_MACHINE
deepspeed_config:
  gradient_accumulation_steps: 1
  offload_optimizer_device: NONE
  zero_stage: 3
distributed_type: DEEPSPEED
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 8
use_cpu: false
```

If I run this, I get a key error:

```
  File "/.../site-packages/accelerate/accelerator.py", line 240, in mixed_precision
    if self.state.deepspeed_plugin.deepspeed_config["fp16"]["enabled"]:
KeyError: 'fp16'
```

I am on python 3.7 and using accelerate  0.6.1 and deepspeed 0.6.1

I suspect the issue is caused by this line:
https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L274

which is querying the config that is written on this line:
https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils.py#L726
which does not have the keys in question
