### ISSUE TITLE
In 1.0, 'auto' values in a DS config are no longer interpolated when using DS-3.

### ISSUE THREAD

**Issue by bradfox2** [huggingface/accelerate#3152]
### System Info

Code that has worked fine for year(s) on <=0.34.1 breaks with 1.0, with no other changes. 

Training with Deepspeed Stage 3, not using the HF Trainer, and simply using `accelerator.prepare`, the 'auto' values are no longer interpolated, and the deepspeed assertions raise a str to int comparison error.  This was not the case in < 1.0 and a rollback to 0.34 fixes it immediately.

DS Config:
```JSON
{
  "bf16": {
    "enabled": true
  },
  "zero_optimization": {
    "stage": 3,
    "allgather_partitions": true,
    "allgather_bucket_size": 1e9,
    "overlap_comm": true,
    "reduce_scatter": true,
    "reduce_bucket_size": 1e9,
    "contiguous_gradients": true,
    "stage3_gather_16bit_weights_on_model_save": true
  },
  "gradient_clipping": "auto",
  "gradient_accumulation_steps": "auto",
  "steps_per_print": 2000,
  "train_batch_size": "auto",
  "train_micro_batch_size_per_gpu": "auto",
  "wall_clock_breakdown": false
}
```

Accelerate config:

```YAML
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_config_file: [see above]
  deepspeed_hostfile: mpi-hostfile.txt
  deepspeed_multinode_launcher: standard
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: "no"
enable_cpu_affinity: false
machine_rank: 0
main_process_ip: 10.1.0.4
main_process_port: 6001
main_training_function: main
num_machines: 2
num_processes: 16
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
```


### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Upgrade to 1.0

### Expected behavior

The 'auto' values are interpolated with actual figures properly.
