### ISSUE TITLE
how to save a model with FSDP2 ?

### ISSUE THREAD

**Issue by colinzhaoxp** [huggingface/accelerate#3633]
Hello everyone, I’m confused about how to save model weights using FSDP2. I keep running into OOM (out-of-memory) issues when trying to save a trained 8B model with FSDP2. Interestingly, memory is sufficient during training, but saving the model requires too much memory.

I would like each rank to save only its own weights.

I’m using 8 A100-40GB GPUs, and I’d really appreciate your help.

here is my envs:
```text
accelereate==1.7.0
torch==2.6.0+cu12.6
transformers==4.52.4
```

this is my accelerate config (FSDP2.ymal):
```yaml
compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
fsdp_config:
  fsdp_activation_checkpointing: false
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_cpu_ram_efficient_loading: true
  fsdp_offload_params: false
  fsdp_reshard_after_forward: true
  fsdp_state_dict_type: SHARDED_STATE_DICT
  fsdp_version: 2
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

my script (demo.py):
```python
import os
import os.path as osp

import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModelForCausalLM

from accelerate import Accelerator

class Mydataset(torch.utils.data.Dataset):
    def __init__(self, data_length=32, tokenizer = None):
        super().__init__()
        self.data_length = data_length
        self.tokenizer = tokenizer
        self.input_str = 'this is a test'
        self.data = tokenizer(self.input_str, return_tensors='pt', padding='max_length', max_length=32, padding_side='right')

    def __len__(self):
        return 10
    
    def __getitem__(self, idx):
        return {
            'input_ids': self.data['input_ids'][0],
            'attention_mask': self.data['attention_mask'][0]
        }


if __name__ == '__main__':

    accelerator = Accelerator()
    model_path = "./pretrain/Qwen3-8B"

    model = AutoModelForCausalLM.from_pretrained(model_path, trust_remote_code=True)
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)

    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

    dataset = Mydataset(tokenizer=tokenizer)
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=16, shuffle=True)

    model, optimizer, dataloader = accelerator.prepare(model, optimizer, dataloader)

    loss_fuc = torch.nn.CrossEntropyLoss()

    model.train()
    # training
    for batch in dataloader:
        input_ids = batch['input_ids']
        attention_mask = batch['attention_mask']
        labels = batch['input_ids'].clone()

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)

        labels = nn.functional.pad(labels, (0, 1), value=-100)
        shift_labels = labels[..., 1:].contiguous().view(-1)

        accelerator.wait_for_everyone()
        loss = loss_fuc(outputs.logits.view(-1, outputs.logits.shape[-1]), shift_labels)
        accelerator.backward(loss)

        optimizer.step()
        optimizer.zero_grad()

    print("training finished")
    model.eval()
    model_save_path = "./saved_models/tmp"

    accelerator.save_model(model, model_save_path)
    print("Done")
```

command:
```bash
accelerate launch --config_file ./accelerate_configs/FSDP2.yaml demo.py
```
