### ISSUE TITLE
`accelerate test` ignores --config-file

### ISSUE THREAD

**Issue by Guitaricet** [huggingface/accelerate#53]
Hi,
Great package, it helped me a lot today! So far it is as simple as it seems 🎉

I noticed that `accelerate test --config_file accelerate_config.yml` uses default config values instead of the values from `accelerate_config.yml`. To test this create an `accelerate_config.yml` file with the contents different from your main config. For example, say that the default config has `num_processes=3`, but you want to only use 2 GPUs and create a config like this.

```yaml
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
fp16: false
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
num_machines: 1
num_processes: 2
```

after running `accelerate test --config_file accelerate_config.yml` you will see something like this

```
Distributed environment: MULTI_GPU
Num processes: 3
Process index: 1
Local process index: 1
Device: cuda:1
Use FP16 precision: False

Distributed environment: MULTI_GPU
Num processes: 3
Process index: 2
Local process index: 2
Device: cuda:2
Use FP16 precision: False

**Initialization**
Testing, testing. 1, 2, 3.
Distributed environment: MULTI_GPU
Num processes: 3
Process index: 0
Local process index: 0
Device: cuda:0
Use FP16 precision: False
```

three GPUs instead of the specified 2.

This happens because `accelerate-launch` requires all keyword arguments to precede the training script path, but `accelerate-test` does this

https://github.com/huggingface/accelerate/blob/9b0dad4c64c170ab0780ad465ce95019f536bb28/src/accelerate/commands/test.py#L51

so what happens is that `--config_file` is recognized as a training script argument instead of launch script argument. You can see it if you print out `args` of the corresponding `accelerate-launch`.

Sending a PR with a fix soon.
