### ISSUE TITLE
Integrate Intel Extension for Pytorch into accelerate to get out-of-box optimizations on intel platform.

### ISSUE THREAD

**Issue by tangleintel** [huggingface/accelerate#700]
### Motivation
Intel Extension for Pytorch provides extra optimization and performance boost on intel platform for both inference and training. Integrate it into accelerate can make users who use distributed training or evaluation get out-of-box performance boost on intel hardware.

#### User interface

- The first thing is how we tell accelerate to enable ipex. We design to extend the accelerate class's constructor with an additional argument 'use_ipex' to indicate wether we will use ipex in accelerate and the default value of this argument is False, thus explicitly tell accelerate if we want to use IPEX. Such as:

```
class Accelerator:
    def __init__(
        self,
        device_placement: bool = True,
        split_batches: bool = False,
        fp16: bool = None,
        mixed_precision: Union[PrecisionType, str] = None,
        gradient_accumulation_steps: int = 1,
        cpu: bool = False,
        deepspeed_plugin: DeepSpeedPlugin = None,
        fsdp_plugin: FullyShardedDataParallelPlugin = None,
        rng_types: Optional[List[Union[str, RNGType]]] = None,
        log_with: Optional[List[Union[str, LoggerType, GeneralTracker]]] = None,
        logging_dir: Optional[Union[str, os.PathLike]] = None,
        dispatch_batches: Optional[bool] = None,
        step_scheduler_with_optimizer: bool = True,
        kwargs_handlers: Optional[List[KwargsHandler]] = None,
        use_ipex: bool = False,
    ):

accelerate = Accecerator(use_ipex=True)
```
If we set use_ipex equals True, we will import the package in the constructor if available. 
- Model and optimizer wrapper for distributed training. 
```
model, optim, data = accelerator.prepare(model, optim, data)
```
Accelerator.prepare() is the main method where most magic happens, IPEX can also hidden optimization magic via a similar front end API called ipex.optimize(). If we choose use ipex, then we can automatically invoke ipex's API inside prepare() according to different distribute configuration. So, no code change in the user interface side.

- Auto Mixed Precision
In CPU side, currently we only support bf16 half precision, we can further extend the ability of AMP on CPU side.

**Comment by pacman100** [comment]
Hello @tangleintel, Thank you for the detailed feature request. I've made the above draft PR. I currently don't have access to instance with latest Intel CPUs to perform the initial testing. Could you please try it out on your end and let us know.
You can enable ipex via below options:
1. Through  `accelerate config` as shown below:
```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_CPU
downcast_bf16: 'no'
fsdp_config: {}
ipex_config:
  ipex_enabled: true
  ipex_fusion_enabled: false
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 4
rdzv_backend: static
same_network: true
use_cpu: true
```
2. Pass `--ipex_enabled` and `--ipex_fusion_enabled` to enable the corresponding options while using `accelerate lauch`, e.g., `accelerate launch --config_file xxxxx.yaml  --ipex_enabled --ipex_fusion_enabled script.py`
