### ISSUE TITLE
use accelerate to resume checkpoint raise IndexError: tuple index out of range

### ISSUE THREAD

**Issue by trouble-maker007** [huggingface/accelerate#784]
### System Info

```Shell
accelerate 0.13.2
torch 1.8.1
transformers 4.21.0
```

### Information

- [X] The official example scripts
- [ ] My own modified scripts

### Tasks

- [X] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

I run my own dataset with `run_no_trainer_glue.py`, the task is like a two class classification, while I try to resume the checkpoint of middle epoch
```
accelerator.load_state(args.resume_from_checkpoint)
resume_step = None
path = args.resume_from_checkpoint
```

raise error
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/73164596/197369920-9b80eb98-a6d9-4bdc-8adf-b45accb4e445.png">

### Expected behavior

```Shell
It should be resume success and continue to training
```

**Comment by sgugger** [comment]
It looks like you are resuming training with less GPUs than what you had for the initial training, which is not supported.

**Comment by trouble-maker007** [comment]
@sgugger I use one node one gpu, here is my config.yaml file

```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
# mixed_precision: fp16
num_machines: 1
num_processes: 1
use_cpu: false
```

**Comment by trouble-maker007** [comment]
@sgugger would you like give some suggestions?

**Comment by sgugger** [comment]
My suggestion is to resume training on the same exact setup as the initial training. As said above, resuming training on a different setup is not supported.

**Comment by trouble-maker007** [comment]
@sgugger but I did not change config file during training and resume? Is it mean that I did not change the config file is equal to resume training on the same exact setup as the initial training.

```
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
# mixed_precision: fp16
num_machines: 1
num_processes: 1
use_cpu: false
```

**Comment by muellerzr** [comment]
@trouble-maker007 I can't reproduce this minimally, such as:
```python
from accelerate import Accelerator
from torchvision.models import resnet34
from fastcore.script import call_parse

def save(accelerator:Accelerator):
    # First bring in the model
    model = resnet34(weights="DEFAULT")
    # Then Accelerator
    model = accelerator.prepare(model)
    accelerator.save_state("test_save")

def load(accelerator:Accelerator):
    # Then load it back in
    accelerator.load_state("test_save")

@call_parse
def main(
    do_load:bool=False, # Whether to save or load the model
):
    accelerator = Accelerator()
    if do_load:
        load(accelerator)
    else:
        save(accelerator)
```

My config looks like such:
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false
```

Are you using `accelerate launch` to run your script in both?

**Comment by muellerzr** [comment]
@trouble-maker007 I can't recreate this based on the following minimal example:

```python
from accelerate import Accelerator
from torchvision.models import resnet34
from fastcore.script import call_parse

def save(accelerator:Accelerator):
    # First bring in the model
    model = resnet34(weights="DEFAULT")
    # Then Accelerator
    model = accelerator.prepare(model)
    accelerator.save_state("test_save")

def load(accelerator:Accelerator):
    model = resnet34(weights="DEFAULT")
    model = accelerator.prepare(model)
    # Then load it back in
    accelerator.load_state("test_save")

@call_parse
def main(
    do_load:bool=False, # Whether to save or load the model
):
    accelerator = Accelerator()
    if do_load:
        load(accelerator)
    else:
        save(accelerator)
```

And this config:
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: 'no'
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
use_cpu: false
```
I ran it once to save then again separately to do the loading. How are you launching training each time? Are you using `accelerate launch` directly? Are you just doing `accelerate launch myscript`?
