### ISSUE TITLE
Multi-GPU doesn't work

### ISSUE THREAD

**Issue by liu6381810** [huggingface/accelerate#847]
Hi, when i run `accelerate launch my_scripy.py`  it seems do nothing even `my_scripy.py` only contain `print(1)`
But if i use one-gpu setting, `print(1)` work as expected

here is my accelerate env；
- `Accelerate` version: 0.14.0
- Platform: Linux-5.4.143.bsk.7-amd64-x86_64-with-debian-10.13
- Python version: 3.7.3
- Numpy version: 1.21.5
- PyTorch version (GPU?): 1.10.0 (True)
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: MULTI_GPU
        - mixed_precision: no
        - use_cpu: False
        - num_processes: 8
        - machine_rank: 0
        - num_machines: 1
        - gpu_ids: all
        - main_process_ip: None
        - main_process_port: None
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {}
        - fsdp_config: {}
        - megatron_lm_config: {}
        - downcast_bf16: no
        - tpu_name: None
        - tpu_zone: None
        - command_file: None
        - commands: None

**Comment by muellerzr** [comment]
Can you share the entire script you are running?

**Comment by liu6381810** [comment]
> Can you share the entire script you are running?

I run 
`accelerate launch test.py`
the test.py is
`from accelerate import Accelerator 
print(1)`
It's weird this command report nothing even the test.py is not exist

**Comment by muellerzr** [comment]
@liu6381810 I'm afraid I can't recreate this. I have done:

```python
# Contents of test.py
from accelerate import Accelerator

print(1)
```

The config:
```yaml
compute_environment: LOCAL_MACHINE
deepspeed_config: {}
distributed_type: MULTI_GPU
downcast_bf16: 'no'
fsdp_config: {}
gpu_ids: all
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
```

The launch command:

```bash
accelerate launch test.py
```

Can you try again with the above setup?
