### ISSUE TITLE
[feature] assert on ambiguity config when using deepspeed

### ISSUE THREAD

**Issue by stas00** [huggingface/accelerate#936]
OK, so please consider this setup:

```
[...]
deepspeed_config:
  deepspeed_multinode_launcher: standard
  deepspeed_config_file: ds_config.json
  gradient_accumulation_steps: 2
  zero3_init_flag: true
  zero_stage: 2
  zero3_save_16bit_model: true
distributed_type: DEEPSPEED
[...]
```
and `ds_config.json`:
```
{
    "fp16": {
        "enabled": true
    },
    "zero_optimization": {
        "stage": 3,
        "stage3_gather_16bit_weights_on_model_save": false,
        "offload_optimizer": {
            "device": "none"
        },
        "offload_param": {
            "device": "none"
        }
    },
    "gradient_clipping": 1.0,
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": 10,
    "steps_per_print": 2000000
}
```

as you can see we have a potential difficult situation here as there are the same configs defined in multiple places. e.g. `zero3_save_16bit_model`, `gradient_accumulation_steps`, `zero_stage`, etc. with values that don't match! And the user isn't the wiser which of them prevail.

Here is my proposal: 

If `deepspeed_config_file` is provided, Accelerate should assert on any other configs that will collide with it. And unless I'm missing some details, I think the only valid (unique) entries of `deepspeed_config` that aren't in the DS config file are:
```
deepspeed_config:
  deepspeed_multinode_launcher: standard
  deepspeed_config_file: ds_config.json
  zero3_init_flag: true
distributed_type: DEEPSPEED
```

and any other deepspeed_config entries create ambiguity and should be asserted on.

And of course if `deepspeed_config_file` is not provided, then of course all those other options are a must.

OK, but then we have the `auto` feature which is useful when things are set elsewhere. So the categorical proposition I made above is probably incorrect. Yet, as you can see from the test case I presented - there is a massive mismatch between the 2 config files and accelerate doesn't assert on that at all. This situation makes debugging extremely painful since I can never be sure if I changed the right config and I'm testing the right combination. And yes, I can look at the logs, but this is not conducive for easy debug.

for context: I spent several days debugging a bad memory leak in m4, triggered by `zero.Init` and I had to switch multiple flags on/off while doing the debug many times again and again.

Thank you!
